# view all routes: app/console debug:router
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: /1.0/docs

hip_app:
    resource: "@HipAppBundle/Resources/config/routing.yml"
    prefix: /1.0

api_login_check:
    path: /1.0/login_check
    methods: [POST]
