security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:

        login:
            pattern:   ^/1.0/login_check
            provider:  fos_userbundle
            stateless: true
            anonymous: true
            form_login:
                login_path:               /1.0/logins
                check_path:               /1.0/login_check
                username_parameter:       _username
                password_parameter:       _password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api:
            pattern:   ^/1.0
            provider:  fos_userbundle
            stateless: true
            anonymous: true
            lexik_jwt: ~

    access_control:
        # Unlocked pages
        - { path: ^/1.0/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/1.0/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/1.0/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/1.0/home, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/1.0/page, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/1.0/post, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/1.0/menu, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/1.0/docs, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # Logged in users only
        - { path: ^/1.0/secure, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/1.0/profiles, roles: IS_AUTHENTICATED_FULLY }
        # Admin users only
        - { path: ^/1.0/users, role: ROLE_SUPER_ADMIN }
        - { path: ^/1.0/contents, role: ROLE_SUPER_ADMIN }
        # Everything else
        - { path: ^/1.0, role: ROLE_SUPER_ADMIN }
